### ISSUE TITLE
Index out of bounds error

### ISSUE THREAD

**Issue by cbryant42** [EQuiw/2019-scalingattack#4]
Hi, thank you so much for posting this code. Your studies have been very helpful with my learning. 

However, I'm getting an index -1 is out of bounds error when running "tutorial/defense2/step2_adaptive.py" with my own images using "load_color_image_example_from_disk". 

This error traces:
"`tutorial/defense2/step2_adaptive.py`" -> Line "`adaptiveattackimage = adaptiveattack.counter_attack(att_image=result_attack_image)`"

"`attack\adaptive_attack\AdaptiveMedianAttack.py`" -> Line "`re = self.__apply_attack(att_image=att_image[:, :, ch], binary_mask=binary_mask)`"

"`attack\adaptive_attack\AdaptiveMedianAttack.py`" -> Line "`cur_median = MedianFilteringDefense.get_median_nan(cur_block)`"

"`defenses\prevention\MedianFilteringDefense.py`" -> Line "`return arr[median_it1]`"

I hope the errors help to debug, let me know your thoughts!

Thanks!

**Comment by EQuiw** [comment]
First of all, thank you for the opened issue. 

Unfortunately, I cannot reproduce the error. Can you provide an example with a source- and target-image that you're loading?
(to my e-mail address is e.quiring@tu-bs.de ). 
Have you tried to use the cython version with `usecythonifavailable = True` in step2_adaptive.py?

**Comment by EQuiw** [comment]
I've closed the issue, since we could not reproduce the error on multiple systems. With more information, I would try to solve it of course.
