### ISSUE TITLE
Image-scaling Attack: How to save output image?

### ISSUE THREAD

**Issue by MichaelTJC96** [EQuiw/2019-scalingattack#9]
I was thinking of saving the output image from the attack by using the function found in your code: “save_jpeg_image”. However, I do not understand the format of parameters to be used in the function. For instance, what is the format for “out_img”? And what does the “quality” parameter means?
 
![image](https://user-images.githubusercontent.com/53596227/126064102-40c38adc-a20b-46eb-8246-c5bf46c970af.png)

Is the following example correct when I am using it in the tutorial code?
 
![image](https://user-images.githubusercontent.com/53596227/126064104-85d48cc9-8077-4978-b5de-5e14cda52312.png)

Also, I would like to enquire on whether how do you measure the effectiveness of the image-scaling attack against machine learning (i.e. federated learning)?

**Comment by EQuiw** [comment]
The function takes a respective numpy array which represents one image.

Regarding your code, just submit one image with each call. For example:
```
tardir = "DIRECTORY-where-you-want-to-save-the-images" # please replace!
save_jpeg_image(src_image_example, os.path.join(tardir,'src_image_example.jpg'), quality=80)
save_jpeg_image(result_attack_image, os.path.join(tardir,'result_attack_image.jpg'), quality=80)
```
Quality refers to the JPEG quality of the saved image. 

Regarding the question about the measurement: the experimental setup is described in our [paper](https://www.sec.cs.tu-bs.de/pubs/2020-sec.pdf).

Thanks for your questions.
